//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MsTimeReportMail.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("marco.tasselli@microsoft.com;a-homujy@microsoft.com")]
        public string ToRecipient {
            get {
                return ((string)(this["ToRecipient"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("andrea.bombelli@reti.it")]
        public string CcRecipient {
            get {
                return ((string)(this["CcRecipient"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ciao, <br/> ecco il time report della settimana. <br/><br/>")]
        public string Body {
            get {
                return ((string)(this["Body"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width=371 style=" +
            "\'width:278.1pt;margin-left:-.05pt;border-collapse:collapse\'><tr style=\'height:10" +
            ".05pt\'><td nowrap valign=bottom style=\'border-top:#9BC2E6;border-left:#9BC2E6;bo" +
            "rder-bottom:windowtext;border-right:windowtext;border-style:solid;border-width:1" +
            ".0pt;background:#1F4E78;padding:0cm 3.5pt 0cm 3.5pt;height:10.05pt\'><p class=Mso" +
            "Normal align=center style=\'mso-margin-top-alt:auto;mso-margin-bottom-alt:auto;te" +
            "xt-align:center\'><b><span style=\'font-size:8.0pt;font-family:\"Tahoma\",sans-serif" +
            ";color:white\'>Work date</span></b><o:p></o:p></p></td><td nowrap valign=bottom s" +
            "tyle=\'border-top:solid #9BC2E6 1.0pt;border-left:none;border-bottom:solid window" +
            "text 1.0pt;border-right:solid windowtext 1.0pt;background:#1F4E78;padding:0cm 3." +
            "5pt 0cm 3.5pt;height:10.05pt\'><p class=MsoNormal style=\'mso-margin-top-alt:auto;" +
            "mso-margin-bottom-alt:auto\'><b><span style=\'font-size:8.0pt;font-family:\"Tahoma\"" +
            ",sans-serif;color:white\'>Risorsa</span></b><o:p></o:p></p></td><td nowrap valign" +
            "=bottom style=\'border-top:solid #9BC2E6 1.0pt;border-left:none;border-bottom:sol" +
            "id windowtext 1.0pt;border-right:solid #9BC2E6 1.0pt;background:#1F4E78;padding:" +
            "0cm 3.5pt 0cm 3.5pt;height:10.05pt\'><p class=MsoNormal style=\'mso-margin-top-alt" +
            ":auto;mso-margin-bottom-alt:auto\'><b><span style=\'font-size:8.0pt;font-family:\"T" +
            "ahoma\",sans-serif;color:white\'>Ore</span></b><o:p></o:p></p></td></tr><tr style=" +
            "\'height:10.05pt\'><td nowrap valign=bottom style=\'border-top:none;border-left:sol" +
            "id #9BC2E6 1.0pt;border-bottom:solid windowtext 1.0pt;border-right:solid windowt" +
            "ext 1.0pt;background:#DDEBF7;padding:0cm 3.5pt 0cm 3.5pt;height:10.05pt\'><p clas" +
            "s=MsoNormal><i>_date1_</i><o:p></o:p></p></td><td nowrap valign=bottom style=\'bo" +
            "rder-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;border-right" +
            ":solid windowtext 1.0pt;background:#DDEBF7;padding:0cm 3.5pt 0cm 3.5pt;height:10" +
            ".05pt\'><p class=MsoNormal><span style=\'font-size:10.0pt;font-family:\"Calibri\",sa" +
            "ns-serif\'><i>_user_</i><o:p></o:p></span></p></td><td nowrap valign=top style=\'b" +
            "order-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;border-righ" +
            "t:solid #9BC2E6 1.0pt;background:#DDEBF7;padding:0cm 3.5pt 0cm 3.5pt;height:10.0" +
            "5pt\'><p class=MsoNormal style=\'mso-margin-top-alt:auto;mso-margin-bottom-alt:aut" +
            "o\'><span style=\'font-size:8.0pt;font-family:\"Tahoma\",sans-serif;color:black\'>&nb" +
            "sp;</span><o:p></o:p></p></td></tr><tr style=\'height:10.05pt\'><td nowrap valign=" +
            "bottom style=\'border-top:none;border-left:solid #9BC2E6 1.0pt;border-bottom:soli" +
            "d windowtext 1.0pt;border-right:solid windowtext 1.0pt;background:#DDEBF7;paddin" +
            "g:0cm 3.5pt 0cm 3.5pt;height:10.05pt\'><p class=MsoNormal><i>_date2_</i><o:p></o:" +
            "p></p></td><td nowrap valign=bottom style=\'border-top:none;border-left:none;bord" +
            "er-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;background:" +
            "#DDEBF7;padding:0cm 3.5pt 0cm 3.5pt;height:10.05pt\'><p class=MsoNormal><span sty" +
            "le=\'font-size:10.0pt;font-family:\"Calibri\",sans-serif\'><i>_user_</i><o:p></o:p><" +
            "/span></p></td><td nowrap valign=top style=\'border-top:none;border-left:none;bor" +
            "der-bottom:solid windowtext 1.0pt;border-right:solid #9BC2E6 1.0pt;background:#D" +
            "DEBF7;padding:0cm 3.5pt 0cm 3.5pt;height:10.05pt\'></td></tr><tr style=\'height:10" +
            ".05pt\'><td nowrap valign=bottom style=\'border-top:none;border-left:solid #9BC2E6" +
            " 1.0pt;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;" +
            "background:#DDEBF7;padding:0cm 3.5pt 0cm 3.5pt;height:10.05pt\'><p class=MsoNorma" +
            "l><i>_date3_</i><span style=\'font-size:10.0pt;font-family:\"Calibri\",sans-serif\'>" +
            "<o:p></o:p></span></p></td><td nowrap valign=bottom style=\'border-top:none;borde" +
            "r-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1" +
            ".0pt;background:#DDEBF7;padding:0cm 3.5pt 0cm 3.5pt;height:10.05pt\'><p class=Mso" +
            "Normal><span style=\'font-size:10.0pt;font-family:\"Calibri\",sans-serif\'><i>_user_" +
            "</i><o:p></o:p></span></p></td><td nowrap valign=top style=\'border-top:none;bord" +
            "er-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid #9BC2E6 1.0" +
            "pt;background:#DDEBF7;padding:0cm 3.5pt 0cm 3.5pt;height:10.05pt\'><p class=MsoNo" +
            "rmal style=\'mso-margin-top-alt:auto;mso-margin-bottom-alt:auto\'><span style=\'fon" +
            "t-size:8.0pt;font-family:\"Tahoma\",sans-serif;color:black\'>&nbsp;</span><o:p></o:" +
            "p></p></td></tr><tr style=\'height:10.05pt\'><td nowrap valign=bottom style=\'borde" +
            "r-top:none;border-left:solid #9BC2E6 1.0pt;border-bottom:solid windowtext 1.0pt;" +
            "border-right:solid windowtext 1.0pt;background:#DDEBF7;padding:0cm 3.5pt 0cm 3.5" +
            "pt;height:10.05pt\'><p class=MsoNormal><i>_date4_</i><o:p></o:p></p></td><td nowr" +
            "ap valign=bottom style=\'border-top:none;border-left:none;border-bottom:solid win" +
            "dowtext 1.0pt;border-right:solid windowtext 1.0pt;background:#DDEBF7;padding:0cm" +
            " 3.5pt 0cm 3.5pt;height:10.05pt\'><p class=MsoNormal><span style=\'font-size:10.0p" +
            "t;font-family:\"Calibri\",sans-serif\'><i>_user_</i><o:p></o:p></span></p></td><td " +
            "nowrap valign=top style=\'border-top:none;border-left:none;border-bottom:solid wi" +
            "ndowtext 1.0pt;border-right:solid #9BC2E6 1.0pt;background:#DDEBF7;padding:0cm 3" +
            ".5pt 0cm 3.5pt;height:10.05pt\'><p class=MsoNormal style=\'mso-margin-top-alt:auto" +
            ";mso-margin-bottom-alt:auto\'><span style=\'font-size:8.0pt;font-family:\"Tahoma\",s" +
            "ans-serif;color:black\'>&nbsp;</span><o:p></o:p></p></td></tr><tr style=\'height:1" +
            "0.05pt\'><td nowrap valign=bottom style=\'border-top:none;border-left:solid #9BC2E" +
            "6 1.0pt;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt" +
            ";background:#DDEBF7;padding:0cm 3.5pt 0cm 3.5pt;height:10.05pt\'><p class=MsoNorm" +
            "al><i>_date5_</i><o:p></o:p></p></td><td nowrap valign=bottom style=\'border-top:" +
            "none;border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid wi" +
            "ndowtext 1.0pt;background:#DDEBF7;padding:0cm 3.5pt 0cm 3.5pt;height:10.05pt\'><p" +
            " class=MsoNormal><span style=\'font-size:10.0pt;font-family:\"Calibri\",sans-serif\'" +
            "><i>_user_</i><o:p></o:p></span></p></td><td nowrap valign=top style=\'border-top" +
            ":none;border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid #" +
            "9BC2E6 1.0pt;background:#DDEBF7;padding:0cm 3.5pt 0cm 3.5pt;height:10.05pt\'></td" +
            "></tr></table>")]
        public string WorkTable {
            get {
                return ((string)(this["WorkTable"]));
            }
        }
    }
}
