//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MsTimeReportMail.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("marco.tasselli@microsoft.com;a-homujy@microsoft.com;a-larasi@microsoft.com")]
        public string ToRecipient {
            get {
                return ((string)(this["ToRecipient"]));
            }
            set {
                this["ToRecipient"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("andrea.bombelli@reti.it")]
        public string CcRecipient {
            get {
                return ((string)(this["CcRecipient"]));
            }
            set {
                this["CcRecipient"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<table  border=0 cellspacing=0 cellpadding=0 width=371 style=\'width:278.1pt;margi" +
            "n-left:-.05pt;border-collapse:collapse\'>\r\n<tr style=\'height:10.05pt\'><td nowrap " +
            "valign=bottom style=\'border-top:#9BC2E6;border-left:#9BC2E6;border-bottom:window" +
            "text;border-right:windowtext;border-style:solid;border-width:1.0pt;background:#1" +
            "F4E78;padding:0cm 3.5pt 0cm 3.5pt;height:10.05pt\'><p align=center style=\'mso-mar" +
            "gin-top-alt:auto;mso-margin-bottom-alt:auto;text-align:center\'> <b><span style=\'" +
            "font-size:10.0pt;color:white;font-family:Segoe UI symbol;\'>Work date</span></b><" +
            "/o:p> </p> </td><td nowrap valign=bottom style=\'border-top:solid #9BC2E6 1.0pt;b" +
            "order-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowte" +
            "xt 1.0pt;background:#1F4E78;padding:0cm 3.5pt 0cm 3.5pt;height:10.05pt\'><p style" +
            "=\'mso-margin-top-alt:auto;mso-margin-bottom-alt:auto\'><b><span style=\'font-size:" +
            "10.0pt;color:white;font-family:Segoe UI symbol;\'>Risorsa</span></b></p> </td> <t" +
            "d nowrap valign=bottom style=\'border-top:solid #9BC2E6 1.0pt;border-left:none;bo" +
            "rder-bottom:solid windowtext 1.0pt;border-right:solid #9BC2E6 1.0pt;background:#" +
            "1F4E78;padding:0cm 3.5pt 0cm 3.5pt;height:10.05pt\'><p style=\'mso-margin-top-alt:" +
            "auto;mso-margin-bottom-alt:auto\'><b><span style=\'font-size:10.0pt;color:white;fo" +
            "nt-family:segoe ui symbol\'>Ore</span></b></p> </td> </tr>\r\n<tr style=\'height:10." +
            "05pt\'><td nowrap valign=bottom style=\'border-top:none;border-left:solid #9BC2E6 " +
            "1.0pt;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;b" +
            "ackground:#DDEBF7;padding:0cm 3.5pt 0cm 3.5pt;height:10.05pt\'><p style=\'font-fam" +
            "ily:segoe ui symbol\'><i>_date1_</i></p></td><td nowrap valign=bottom style=\'bord" +
            "er-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;border-right:s" +
            "olid windowtext 1.0pt;background:#DDEBF7;padding:0cm 3.5pt 0cm 3.5pt;height:10.0" +
            "5pt\'><p style=\'font-family:segoe ui symbol\'><span style=\'font-size:10.0pt;font-f" +
            "amily:\"segoe ui symbol\",sans-serif\'><i>_user_</i></span></p></td><td nowrap vali" +
            "gn=top style=\'border-top:none;border-left:none;border-bottom:solid windowtext 1." +
            "0pt;border-right:solid #9BC2E6 1.0pt;background:#DDEBF7;padding:0cm 3.5pt 0cm 3." +
            "5pt;height:10.05pt\'><span style=\'font-size:10.0pt;color:black;font-family:\"Segoe" +
            " UI Symbol\"\'>&nbsp;</span></td></tr>\r\n<tr style=\'height:10.05pt\'><td nowrap vali" +
            "gn=bottom style=\'border-top:none;border-left:solid #9BC2E6 1.0pt;border-bottom:s" +
            "olid windowtext 1.0pt;border-right:solid windowtext 1.0pt;background:#DDEBF7;pad" +
            "ding:0cm 3.5pt 0cm 3.5pt;height:10.05pt\'><p style=\'font-family:segoe ui symbol\'>" +
            "<i>_date2_</i></p></td><td nowrap valign=bottom style=\'border-top:none;border-le" +
            "ft:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt" +
            ";background:#DDEBF7;padding:0cm 3.5pt 0cm 3.5pt;height:10.05pt\'><p style=\'font-f" +
            "amily:segoe ui symbol\'><span style=\'font-size:10.0pt;font-family:\"segoe ui symbo" +
            "l\",sans-serif\'><i>_user_</i></span></p></td><td nowrap valign=top style=\'border-" +
            "top:none;border-left:none;border-bottom:solid windowtext 1.0pt;border-right:soli" +
            "d #9BC2E6 1.0pt;background:#DDEBF7;padding:0cm 3.5pt 0cm 3.5pt;height:10.05pt\'><" +
            "span style=\'font-size:10.0pt;color:black;font-family:\"Segoe UI Symbol\"\'>&nbsp;</" +
            "span></td></tr>\r\n<tr style=\'height:10.05pt\'><td nowrap valign=bottom style=\'bord" +
            "er-top:none;border-left:solid #9BC2E6 1.0pt;border-bottom:solid windowtext 1.0pt" +
            ";border-right:solid windowtext 1.0pt;background:#DDEBF7;padding:0cm 3.5pt 0cm 3." +
            "5pt;height:10.05pt\'><p style=\'font-family:segoe ui symbol\'><i>_date3_</i></p></t" +
            "d><td nowrap valign=bottom style=\'border-top:none;border-left:none;border-bottom" +
            ":solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;background:#DDEBF7;p" +
            "adding:0cm 3.5pt 0cm 3.5pt;height:10.05pt\'><p style=\'font-family:segoe ui symbol" +
            "\'><span style=\'font-size:10.0pt;font-family:\"segoe ui symbol\",sans-serif\'><i>_us" +
            "er_</i></span></p></td><td nowrap valign=top style=\'border-top:none;border-left:" +
            "none;border-bottom:solid windowtext 1.0pt;border-right:solid #9BC2E6 1.0pt;backg" +
            "round:#DDEBF7;padding:0cm 3.5pt 0cm 3.5pt;height:10.05pt\'><span style=\'font-size" +
            ":10.0pt;color:black;font-family:\"Segoe UI Symbol\"\'>&nbsp;</span></td></tr>\r\n<tr " +
            "style=\'height:10.05pt\'><td nowrap valign=bottom style=\'border-top:none;border-le" +
            "ft:solid #9BC2E6 1.0pt;border-bottom:solid windowtext 1.0pt;border-right:solid w" +
            "indowtext 1.0pt;background:#DDEBF7;padding:0cm 3.5pt 0cm 3.5pt;height:10.05pt\'><" +
            "p style=\'font-family:segoe ui symbol\'><i>_date4_</i></p></td><td nowrap valign=b" +
            "ottom style=\'border-top:none;border-left:none;border-bottom:solid windowtext 1.0" +
            "pt;border-right:solid windowtext 1.0pt;background:#DDEBF7;padding:0cm 3.5pt 0cm " +
            "3.5pt;height:10.05pt\'><p style=\'font-family:segoe ui symbol\'><span style=\'font-s" +
            "ize:10.0pt;font-family:\"segoe ui symbol\",sans-serif\'><i>_user_</i></span></p></t" +
            "d><td nowrap valign=top style=\'border-top:none;border-left:none;border-bottom:so" +
            "lid windowtext 1.0pt;border-right:solid #9BC2E6 1.0pt;background:#DDEBF7;padding" +
            ":0cm 3.5pt 0cm 3.5pt;height:10.05pt\'><span style=\'font-size:10.0pt;color:black;f" +
            "ont-family:\"Segoe UI Symbol\"\'>&nbsp;</span></td></tr>\r\n<tr style=\'height:10.05pt" +
            "\'><td nowrap valign=bottom style=\'border-top:none;border-left:solid #9BC2E6 1.0p" +
            "t;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;backg" +
            "round:#DDEBF7;padding:0cm 3.5pt 0cm 3.5pt;height:10.05pt\'><p style=\'font-family:" +
            "segoe ui symbol\'><i>_date5_</i></p></td><td nowrap valign=bottom style=\'border-t" +
            "op:none;border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid" +
            " windowtext 1.0pt;background:#DDEBF7;padding:0cm 3.5pt 0cm 3.5pt;height:10.05pt\'" +
            "><p style=\'font-family:segoe ui symbol\'><span style=\'font-size:10.0pt;font-famil" +
            "y:\"segoe ui symbol\",sans-serif\'><i>_user_</i></span></p></td><td nowrap valign=t" +
            "op style=\'border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;" +
            "border-right:solid #9BC2E6 1.0pt;background:#DDEBF7;padding:0cm 3.5pt 0cm 3.5pt;" +
            "height:10.05pt\'><span style=\'font-size:10.0pt;color:black;font-family:\"Segoe UI " +
            "Symbol\"\'>&nbsp;</span></td></tr>\r\n</table>")]
        public string WorkTable {
            get {
                return ((string)(this["WorkTable"]));
            }
            set {
                this["WorkTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<div style=\'font-family:\"Segoe UI Symbol\"; 10.0pt\'>Ciao,<br/>&nbsp;qui di seguito" +
            " il report delle ore lavorate in ENI per la settimana in oggetto. <br/><br/></di" +
            "v>")]
        public string Body {
            get {
                return ((string)(this["Body"]));
            }
            set {
                this["Body"] = value;
            }
        }
    }
}
